name: web_demo
description: A new Flutter project.

publish_to: "none" 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  provider: ^6.0.3
  get_it: ^7.2.0
  cupertino_icons: ^1.0.5
  oktoast: ^3.2.0
  responsive_builder: ^0.4.2
  markdown_widget:
    git:
      url: "https://github.com/asjqkkkk/markdown_widget"
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.3
  go_router: ^3.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/wechat_cobe.jpeg
    - assets/images/logo.png
